#!/bin/sh

set -e

# run from anywhere
APP_DIR_FULL=$(realpath "$0")
APP_DIR=$(dirname "$APP_DIR_FULL")
cd "$APP_DIR" || exit 1

# automatic increase minor version number whith each build
VERSION_FILE="version"
VERSION_MAJOR=$(sed -n '1p' $VERSION_FILE)
VERSION_MINOR=$(sed -n '2p' $VERSION_FILE)
VERSION_MINOR_NEW=$((1 + VERSION_MINOR))
sed -i "2 s/$VERSION_MINOR\$/$VERSION_MINOR_NEW/g" $VERSION_FILE
VERSION="$VERSION_MAJOR.$VERSION_MINOR_NEW"

# variables
NAME="vmh"
README="README.md"
RELEASES="releases"
TARGET="DEBIAN"
MAN_PAGE=1
FILE_MAN="$NAME.$MAN_PAGE"
PATH_BASE="./$RELEASES/$NAME-$VERSION"
PATH_INSTALL="$PATH_BASE"
PATH_BASH_COMP="$PATH_BASE/usr/share/bash-completion/completions"
FILE_BASH_COMP="$PATH_BASH_COMP/$NAME"
PATH_BIN="$PATH_INSTALL/bin"
PATH_SHARE="$PATH_INSTALL/usr/share/$NAME"
PATH_TARGET="$PATH_BASE/$TARGET"
PATH_MAN="$PATH_INSTALL/usr/share/man/man$MAN_PAGE"

# delete the old build
echo "Cleaning up old build"
rm -rf "$PATH_BASE"

# copy relevant files from source to release
echo "Copying relevant source files"
mkdir -p "$PATH_SHARE" "$PATH_BIN" "$PATH_MAN" "$PATH_BASH_COMP"
cp -t "$PATH_SHARE" "README.md" "copyright" "no-display.ppm" "vmh.conf" || exit 1
chmod 0755 "$NAME" "virt-viewer-easy" "virt-screenshot"
cp -t "$PATH_BIN" "$NAME" "virt-viewer-easy" "virt-screenshot" || exit 1

# auto generate bash completion
echo "#!/usr/bin/env bash" >"$FILE_BASH_COMP"
# shellcheck disable=SC2129
echo "complete -W \"" >>"$FILE_BASH_COMP"
grep -A 1000 '# select program' <"$NAME" | grep -B 1000 'Unknown action' |
    grep ')' | grep '^[-a-z]' | tr -d ')' >>"$FILE_BASH_COMP"
echo "\" $NAME" >>"$FILE_BASH_COMP"

# build man page
ronn -r <"$README" | gzip -9n >"$PATH_MAN/$FILE_MAN" || exit 1
# get description
DESCRIPTION=$(sed -n -e '1 s/^.*) -- //p' <"$README") || exit 1

# create Debian control file
echo "Creating CONTROL file"
mkdir -p "$PATH_TARGET"
echo "Package: $NAME
Version: $VERSION
Section: admin
Priority: optional
Architecture: all
Depends: qemu-kvm,
 libvirt-clients (>=7),
 libvirt-daemon-system (>=7),
 virt-auto-expand,
 virt-manager,
 rsyslog (>=8),
 libguestfs-tools (>=1),
 rsync (>=3.2),
 waitforit,
 xmlstarlet (>=1.6),
 add-to-hosts,
 csv2netmap,
 csvkit (>=1),
 sort-by-version,
 fonts-dejavu-core,
 bc,
 python3:any | python3-minimal:any
Maintainer: Bodo Endres <dev@muspekaren.se>
Description: $DESCRIPTION
" >"$PATH_TARGET/control"

# build
echo "Building"
fakeroot dpkg-deb --build "$PATH_BASE"

# pack source files
echo "Packing source"
zip -q -r "$RELEASES/$NAME-$VERSION.source.zip" ./* \
    -x $RELEASES\* \
    -x .*\* \
    -x ./*DEV_\*
wait

# replace latest version
cd "$RELEASES" || exit 1
ln -sf "$NAME-$VERSION.deb" "$NAME-LATEST.deb"
ln -sf "$NAME-$VERSION.source.zip" "$NAME-LATEST.source.zip"
cd "$APP_DIR" || exit 1

# clean up
echo "Clean up"
rm -rf "$PATH_BASE"

# check
echo "Checking:"
lintian -c "$PATH_BASE.deb"
