#!/bin/sh
#info: virt-viewer wrapper

set -e

# help
if [ -z "$1" ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    man vmh.1 || ronn -r <README.md | man -l -
    exit
fi

# must run as normal user
if [ "$(id -u)" = 0 ]; then
    echo 'This script must be run as a normal user, not root!' >&2
    exit 1
fi

# set default URI
[ -n "$LIBVIRT_DEFAULT_URI" ] || export LIBVIRT_DEFAULT_URI="qemu:///system"
# set default display
[ -n "$DISPLAY" ] || export DISPLAY=:0

DOMAIN="$1"
ARG="$2"
FULL_ARG=""
if [ "$ARG" = "f" ]; then
    FULL_ARG="-f"
elif [ "$ARG" = "k" ]; then
    FULL_ARG="-k"
fi

error() {
    # logger -t "vmhandler" "ERROR: $DOMAIN: $1"
    echo "ERROR: $DOMAIN: $1" >&2
    exit 1
}

warn() {
    # logger -t "vmhandler" "WARNING: $DOMAIN: $1"
    echo "WARNING: $DOMAIN: $1" >&2
}

info() {
    # logger -t "vmhandler" "INFO: $DOMAIN: $1"
    echo "INFO: $DOMAIN: $1" >&2
}

# verify input
[ -z "$DOMAIN" ] && error "Must specify a DOMAIN"

info "Trying to connect"
# shellcheck disable=SC2086
virt-viewer "$DOMAIN" --reconnect --wait $FULL_ARG 1>/dev/null 2>/dev/null &
