#!/bin/sh

# must run as normal user
if [ "$(id -u)" = 0 ]; then
    echo 'This script must be run as a normal user, not root!' >&2
    exit 1
fi

DOMAIN="$1"
ARG="$2"
FULL_ARG=""
if [ "$ARG" = "-f" ]; then
    FULL_ARG="-f"
elif [ "$ARG" = "-k" ]; then
    FULL_ARG="-k"
fi

error() {
    # logger -t "vmhandler" "ERROR: $DOMAIN: $1"
    echo "ERROR: $DOMAIN: $1" >&2
    exit 1
}

warn() {
    # logger -t "vmhandler" "WARNING: $DOMAIN: $1"
    echo "WARNING: $DOMAIN: $1" >&2
}

info() {
    # logger -t "vmhandler" "INFO: $DOMAIN: $1"
    echo "INFO: $DOMAIN: $1" >&2
}

webinfo() {
    echo "$1"
}

is_imported() {
    if [ -z "$1" ]; then
        error "is_imported: variable is unset or empty"
    fi

    if virsh -q list --all --name | grep -qx "$1"; then
        return 0
    else
        return 1
    fi
}

is_running() {
    if [ -z "$1" ]; then
        error "is_running: variable is unset or empty"
    fi

    if virsh -q list --name --state-running | grep -qx "$1"; then
        return 0
    else
        return 1
    fi
}
if ! is_imported "$DOMAIN"; then
    error "Domain is not imported"
fi
if ! is_running "$DOMAIN"; then
    error "Domain is not running"
fi

info "exporting new display: $DISPLAY"
export DISPLAY=:0 1>&2 # todo: find all displays first
info "trying to connect to: $DOMAIN"
# shellcheck disable=SC2086
virt-viewer "$DOMAIN" -c qemu:///system --reconnect --wait $FULL_ARG \
    1>/dev/null 2>/dev/null &
