#!/bin/sh
#info: Clear log file

# must run as root
if [ "$(id -u)" -ne 0 ]; then
    echo 'This script must be run as root!' >&2
    exit 1
fi

echo "" >/var/log/vmhandler.log
chmod 644 /var/log/vmhandler.log

rm -f /var/log/libvirt/qemu/*.log || true
