#!/bin/sh
#info: Enable VMH in syslog

# must run as root
if [ "$(id -u)" -ne 0 ]; then
	echo 'This script must be run as root!' >&2
	exit 1
fi

# already enabled
if [ -f "/etc/rsyslog.d/99-vmhandler.conf" ]; then
	exit 0
fi

# shellcheck disable=SC2016
echo "\$FileCreateMode 0644
\$umask 0644
:syslogtag, startswith, \"vmhandler\" /var/log/vmhandler.log
& stop
" >"/etc/rsyslog.d/99-vmhandler.conf"

if [ -z "$(command -v systemctl)" ]; then
	echo "systemctl not found. Please restart the rsyslog service manually."
	exit 1
fi

systemctl restart rsyslog.service
